# Pull the latest node
FROM node:latest 

# SET WORKING DIR TO /app INSIDE THE CONTAINER
WORKDIR /app

#COPY PACKAGE.JSON & PACKAGE_LOCK.JSON INTO THE CURRENT DIRECTORY
COPY package*.json ./ 

# RUN NPM INSTALL
RUN npm install 

#COPY OTHER DIRECTORYS TO CURRENT DIR(/app)
COPY . .

# ADD THE PORT TO RUN 
EXPOSE 5000

#COMMANDS
CMD ["npm","start"]
